name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "davyphal8@gmail.com"
          git config --global user.name "da-vy"

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://da-vy:${HF_TOKEN}@huggingface.co/spaces/da-vy/Predictive_Care_System
          git push --force hf main
